[include "omnimorph_robotname.ini"]

[WRAPPER]
# name of the wrapper device to be instatiated by the factory
device controlboardwrapper2
# rate of output streaming from ports in ms
period 2
# output port name (a leading '/' will be added by code)
name /${gazeboYarpPluginsRobotName}/omnimorph_joints
# Total number of joints
joints 8
# list of MotorControl device to use
networks (omnimorph_joints)
# for each network specify the joint map
omnimorph_joints 0 7 0 7
# Verbose output (on if present, off if commented out)
# verbose

[TRAJECTORY_GENERATION]
trajectory_type minimum_jerk

# Specify configuration of MotorControl devices
[omnimorph_joints]
# name of the device to be instatiated by the factory
device gazebo_controlboard
#jointNames list
jointNames jm-1 jm-2 jm-3 jm-4 jm-5 jm-6 jm-7 jm-8
name omnimorphs_joints

min_stiffness 0.0    0.0    0.0    0.0    0.0    0.0   0.0    0.0
max_stiffness 10.0    1.0    1.0    1.0    1.0    1.0   1.0    1.0
min_damping   0.0    0.0    0.0    0.0    0.0    0.0   0.0    0.0
max_damping   1    0.1    0.1    0.1    0.1    0.1   0.1    0.1
max_torques  6 6 6 6 6 6 6 6

#PIDs:
# this information is used to set the PID values in simulation for GAZEBO, we need only the first three values
[POSITION_CONTROL]
controlUnits  metric_units
controlLaw    joint_pid_gazebo_v1
kp            0.003 0.001 0.001 0.001 0.001 0.001 0.001 0.001 
kd            0.0001 0.0001 0.0001 0.0001 0.0001 0.0001 0.0001 0.0001
ki            0.0 0 0 0 0 0 0 0
maxInt        100 1 1 1 1 1 1 1
maxOutput     100 2 2 2 2 2 2 2
shift         0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0
ko            0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0
stictionUp    0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0
stictionDwn   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0

[VELOCITY_CONTROL]
controlUnits  metric_units
controlLaw    joint_pid_gazebo_v1
velocityControlImplementationType direct_velocity_pid
kp            0.008726 0.008726 0.008726 0.008726 0.008726 0.008726 0.008726 0.00872
kd            0.000035 0.000035 0.000035 0.000035 0.000035 0.000035 0.000035 0.000035
ki            0.000002 0.000002 0.000002 0.000002 0.000002 0.000002 0.000002 0.000002
maxInt        9999  9999  9999  9999  9999  9999  9999  9999
maxOutput     9999  9999  9999  9999  9999  9999  9999  9999
shift         0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0
ko            0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0
stictionUp    0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0
stictionDwn   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0

[IMPEDANCE_CONTROL]
controlUnits  metric_units
controlLaw    joint_pid_gazebo_v1
stiffness     0 0 0 0 0 0 0 0 
damping       0 0 0 0 0 0 0 0

[LIMITS]
jntPosMax 180 180 180 180 180 180 180 180
jntPosMin -180 -180 -180 -180 -180 -180 -180 -180
jntVelMax  100.0 100.0 100.0 100.0 100.0 100.0 100.0 100.0
